baseurl = "https://gertvangool.be/"
languageCode = "en-us"
title = "Gert Van Gool"
theme = "casper"
footnotereturnlinkcontents = "â†©"
editor = "vim"
newContentEditor = "vim"

[params]
  #description = "this is my description"
  cover = "assets/img/20100522-0731-2000x1296.jpg"
  author = "Gert Van Gool"
  authorlocation = "Belgium"
  authorwebsite = "https://gertvangool.be"
  bio= "A 32 year old Belgian software developer. Currently working in Berlin."
  #logo = "images/logo.png"
  googleAnalyticsUserID = "UA-24721395-1"
  githubName = "gvangool"
  twitterName = "gvangool"
  #facebookName = "gvangool"
  #linkedinName = "gertvangool"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  PygmentsCodeFences = true
  PygmentsStyle = "solarizedlight"


[permalinks]
  post = "post/:year/:slug/"
  quote = "quote/:slug/"

[[menu.main]]
  name = "Home"
  weight = -500
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Blog"
  weight = -100
  identifier = "blog"
  url = "/post/"

[[menu.main]]
  name = "Quotes"
  weight = -50
  identifier = "quotes"
  url = "/quote/"

[[menu.main]]
  name = "About me"
  weight = 500
  identifier = "about"
  url = "/about/"
